<?php

/**
 * Created by PhpStorm.
 * User: igor
 * Date: 1/27/2016
 * Time: 11:10 PM
 */
class AmericanTest extends PHPUnit_Framework_TestCase
{
    private $component;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->component = new \Pizzeria\Models\Components\American();
    }

    public function testPriceOfOne()
    {
        $this->assertEquals("3", $this->component->getPrice());
    }

    public function testPriceOfHalf()
    {
        $this->component->setFactor(0.5);
        $this->assertEquals("1.5", $this->component->getPrice());
    }

    public function testPriceOfDouble()
    {
        $this->component->setFactor(2);
        $this->assertEquals("6", $this->component->getPrice());

    }

    public function testPriceOfTriple()
    {
        $this->component->setFactor(3);
        $this->assertEquals("9", $this->component->getPrice());
    }
}
