<?php

/**
 * Created by PhpStorm.
 * User: igor
 * Date: 1/27/2016
 * Time: 8:00 PM
 */
class OrderControllerTest extends \PHPUnit_Framework_TestCase
{
    private $orderController;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->orderController = new \Pizzeria\Controllers\OrderController();
    }

    public function testOrderControllerCreation()
    {
        $this->assertEquals("123","123");
    }
}
